services:
  tazuna:
    build: 
      context: .
      args:
        - CACHE_BUST=${CACHE_BUST}
    container_name: tazuna
    # No env_file here — we'll inject secrets from Portainer UI
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      APP_ID: "${APP_ID}"
    ports:
      - "3000:3000"
    restart: unless-stopped
    # If you later use Google Sheets features, mount your service-account key (kept off-repo):
    # volumes:
    #   - /opt/tazuna/credentials.json:/app/assets/credentials.json:ro
# auto-update-timestamp: 20250914233629
