name: Sync upstream → main
on:
  schedule:
    - cron: '*/5 * * * *'   # hourly; adjust as you like
  workflow_dispatch:      # allow manual "Run workflow" from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/JustWastingTime/TazunaDiscordBot.git
          git fetch upstream main

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge --no-edit upstream/main || true

      - name: Update docker-compose.yml comment
        run: |
          TS=$(date +%Y%m%d%H%M%S)
          if grep -q "auto-update-timestamp" docker-compose.yml; then
            sed -i "s/^# auto-update-timestamp.*/# auto-update-timestamp: ${TS}/" docker-compose.yml
          else
            echo "# auto-update-timestamp: ${TS}" >> docker-compose.yml
          fi

      - name: Commit docker-compose.yml update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docker-compose.yml
          git commit -m "Bump docker-compose.yml comment ${TS}" || echo "No changes"

      - name: Push back to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main
